### ISSUE TITLE
Telemetry (Beluga): Investigate Battery sensor

### ISSUE THREAD

**Issue by PizzaAllTheWay** [vortexntnu/vortex-acoustics#92]
- Investigate how it works
- Debug the thing and check if something is wrong from software/hardware side
- Communication protocol must find out

**Comment by TheoHHH** [comment]
Battery sensor that we are using : https://bluerobotics.com/store/comm-control-power/control/psm-asm-r2-rp/

The sensor is connected to the Power Distribution Board, which converts the analog signal to a digital signal (1 V = 11 V in reality). Then this digital signal is transmitted to the raspberry Pie.

The voltage data are accurate and are transmitted properly, but the ADC for the current is broken. 
The problem is that the ADC that we are using with the PDB are not in production anymore so in the future, it would be a good idea to redesign the PDB to be able to use different ADC that are still in production.
